### ISSUE TITLE
How can i get SHORTEST_PATH  when i want to get  A<----->B<----->C

### ISSUE THREAD

**Issue by wqxcloud** [arangodb/spring-data-demo#21]
When i   use "FOR v IN ANY SHORTEST_PATH @_fromDbId TO @_toDbId  relationOf  return v"  to  get the shortestpath from A  to C 
I  get  that  A----->B<-------C    but  I want to  get    A<----->B<----->C,  what  can  i  do use  AQL to  get it? i  want  to  get  the  Strongly Connected Graph.
thanks  for  your  help

**Comment by rashtao** [comment]
To find strongly connected components you can use ArangoDB Pregel: https://www.arangodb.com/docs/stable/graphs-pregel.html#connected-components

**Comment by wqxcloud** [comment]
ok,thanks very much,i try it

**Comment by rashtao** [comment]
No, unfortunately it is not (yet) implemented in the Java driver.

**Comment by wqxcloud** [comment]
> No, unfortunately it is not (yet) implemented in the Java driver.

oh,this is very regret,but how can i do it?

**Comment by rashtao** [comment]
Here you can follow the ongoing work to document the Pregel API: https://github.com/arangodb/arangodb/pull/13607
Support for it will be implemented in the Java driver once the documentation is complete.
In the meantime you can call it creating custom requests using `ArangoDB.execute(Request)`. See https://github.com/arangodb/arangodb-java-driver/blob/f3429b2902556762ded608f069cc4caf8c603162/src/main/java/com/arangodb/ArangoDB.java#L863-L870
